name: pusher_flutter
description: A flutter plugin for Pusher (pusher.com)
version: 0.0.1
author: Matthew Smith <matthew@apptree.cloud>
homepage: https://github.com/apptreesoftware/pusher_flutter

flutter:
  plugin:
    androidPackage: com.apptreesoftware.pusherflutter
    pluginClass: PusherFlutterPlugin

dependencies:
  flutter:
    sdk: flutter
